theme: jekyll-theme-leap-day
title: Assertions for Result
description: Fluent assertions for Result objects
current_version: 0.3.1.0
show_downloads: true
logo: https://dev.leakyabstractions.com/result/result-banner.png
